[package]
name = "rs-dynasip"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
nom = "8.0.0"
rsip = "0.4.0"
dashmap = "6.1.0"
log = "0.4.27"
env_logger = "0.11.8"